/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#ifndef _GUI_H_
#define _GUI_H_

#include "gfx.h"

// GListeners
extern GListener glistener;

// GHandles
extern GHandle ghContainerPage0;
extern GHandle ghButton1;
extern GHandle ghKeyboard1;
extern GHandle ghConsole1;

// Function Prototypes
void guiCreate(void);
void guiShowPage(unsigned pageIndex);

#endif /* _GUI_H_ */

