/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#include "colors.h"
#include "widgetstyles.h"
#include "gui.h"

// GListeners
GListener glistener;

// GHandles
GHandle ghContainerPage0;
GHandle ghButton1;
GHandle ghKeyboard1;
GHandle ghConsole1;

// Fonts
font_t dejavu_sans_10;

static void createPagePage0(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);


	// create container widget: ghContainerPage0
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 240;
	wi.g.height = 320;
	wi.g.parent = 0;
	wi.text = "Container";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerPage0 = gwinContainerCreate(0, &wi, 0);

	// create button widget: ghButton1
	wi.g.show = TRUE;
	wi.g.x = 60;
	wi.g.y = 190;
	wi.g.width = 120;
	wi.g.height = 20;
	wi.g.parent = ghContainerPage0;
	wi.text = "Clear";
	wi.customDraw = gwinButtonDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghButton1 = gwinButtonCreate(0, &wi);

	// Create keyboard widget: ghKeyboard1
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 220;
	wi.g.width = 240;
	wi.g.height = 100;
	wi.g.parent = ghContainerPage0;
	wi.text = "Keyboard1";
	wi.customDraw = gwinKeyboardDraw_Normal;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghKeyboard1 = gwinKeyboardCreate(0, &wi);

	// Create console widget: ghConsole1
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 240;
	wi.g.height = 190;
	wi.g.parent = ghContainerPage0;
	ghConsole1 = gwinConsoleCreate(0, &wi.g);
	gwinSetColor(ghConsole1, white_studio);
	gwinSetBgColor(ghConsole1, black_studio);
}

void guiShowPage(unsigned pageIndex)
{
	// Hide all pages
	gwinHide(ghContainerPage0);

	// Show page selected page
	switch (pageIndex) {
	case 0:
		gwinShow(ghContainerPage0);
		break;

	default:
		break;
	}
}

void guiCreate(void)
{
	GWidgetInit wi;

	// Prepare fonts
	dejavu_sans_10 = gdispOpenFont("DejaVuSans10");

	// Prepare images

	// GWIN settings
	gwinWidgetClearInit(&wi);
	gwinSetDefaultFont(dejavu_sans_10);
	gwinSetDefaultStyle(&black, FALSE);
	gwinSetDefaultColor(white_studio);
	gwinSetDefaultBgColor(black_studio);

	// Create all the display pages
	createPagePage0();

	// Select the default display page
	guiShowPage(0);

	// Console sample text
	gwinPrintf(ghConsole1, "console interface example");
}

