######################################################################
# Automatically generated by qmake (3.0) Sab Apr 26 15:59:09 2014
######################################################################

QT += core gui widgets

TEMPLATE = app
TARGET = windowFlag
INCLUDEPATH += .

# Input
HEADERS += control.h preview.h
SOURCES += control.cpp main.cpp preview.cpp
