######################################################################
# Automatically generated by qmake (3.0) Sab Agt 9 20:56:51 2014
######################################################################

TEMPLATE = app
TARGET = colortrack2
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += /usr/local/include/opencv2
LIBS += -lopencv_core -lopencv_highgui -lopencv_imgproc

# Input
SOURCES += main.cpp
