//id:textlcd_config.h,textlcd,2-8-2012,sidiknur@yahoo.com
#ifndef TEXTLCD_CONFIG_H_INCLUDED
#define TEXTLCD_CONFIG_H_INCLUDED

#define	LCD_DISPLAY_CLEAR		0x01
#define	LCD_CURSOR_HOME			0x02
#define	LCD_ENTRY_MODE_SET		0x04
#define LCD_ENTRY_INCREMENT		(0x02 | LCD_ENTRY_MODE_SET)
#define	LCD_ENTRY_DECREMENT		(0	  | LCD_ENTRY_MODE_SET)
#define LCD_ENTRY_SHIFT			(0x01 | LCD_ENTRY_MODE_SET)
#define	LCD_ENTRY_NOTSHIFT		(0	  | LCD_ENTRY_MODE_SET)
#define	LCD_DISPLAY_ON_OFF		0x08
#define	LCD_DISPLAY_ON			(0x04 | LCD_DISPLAY_ON_OFF)
#define	LCD_DISPLAY_OFF			(0	  | LCD_DISPLAY_ON_OFF)
#define LCD_CURSOR_ON			(0x02 | LCD_DISPLAY_ON_OFF)
#define	LCD_CURSOR_OFF			(0	  | LCD_DISPLAY_ON_OFF)
#define	LCD_POSITION_BLINK		(0x01 | LCD_DISPLAY_ON_OFF)
#define LCD_POSITION_NOTBLINK	(0	  | LCD_DISPLAY_ON_OFF)
#define LCD_CURSOR_DISPLAY_SHIFT 0x10
#define	LCD_DISPLAY_SHIFT		(0x08 | LCD_CURSOR_DISPLAY_SHIFT)
#define	LCD_CURSOR_SHIFT		(0	  | LCD_CURSOR_DISPLAY_SHIFT)
#define	LCD_RIGHT_SHIFT			(0x04 | LCD_CURSOR_DISPLAY_SHIFT)
#define LCD_LEFT_SHIFT			(0	  | LCD_CURSOR_DISPLAY_SHIFT)
#define	LCD_FUNCTION_SET		0x28
#define	LCD_8BIT				(0x10 | LCD_FUNCTION_SET)
#define	LCD_4BIT				(0    | LCD_FUNCTION_SET)
#define	LCD_CGRAM_ADDR_SET		0x40
#define LCD_DDRAM_ADDR_SET		0x80


#endif // TEXTLCD_CONFIG_H_INCLUDED
