#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := console
CFLAGS += -DDEFAULT_N=100

include $(IDF_PATH)/make/project.mk

